version: '3.8'
services:

  # banco de dados
  postgres_test:
    container_name: postgres_test
    build: 
      context: ./
      dockerfile: postgres/Dockerfile.postgres
    hostname: postgres_test
    network_mode: host
    env_file:
      - ./postgres/vars.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  # cache
  redis:
    container_name: redis_test
    build: 
      context: ./
      dockerfile: redis/Dockerfile.redis
    hostname: redis_test
    network_mode: host   
    ports:
      - "6379:6379"


  # test app
  test_app:
    container_name: app_test
    build: 
      context: ./
      dockerfile: app/tests/Dockerfile.tests
    hostname: app_test
    network_mode: host  
    env_file:
      - ./postgres/vars.env
      - ./redis/vars.env
    environment:
      APP_PORT: 8080 
    ports:
      - 8080:8080 
    depends_on:
      postgres_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy
