version: '3.8'
services:

  # banco de dados
  postgres_test:
    container_name: postgres_test
    image: docker.io/postgres
    hostname: postgres_test
    network_mode: host
    env_file:
      - ./postgres/vars.env
    volumes:
      - ./postgres/config.sql:/docker-entrypoint-initdb.d/config.sql
      - ./postgres/table.sql:/docker-entrypoint-initdb.d/table.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  # test app
  test_app:
    container_name: test_app
    build: 
      context: ./
      dockerfile: Dockerfile.tests
    hostname: test_app
    network_mode: host  
    env_file:
      - ./postgres/vars.env
    environment:
      APP_PORT: 8080 
    ports:
      - 8080:8080 
    depends_on:
      postgres_test:
        condition: service_healthy



