version: '3.8'
services:

  # banco de dados
  postgres:
    container_name: postgres
    image: docker.io/postgres
    hostname: postgres
    network_mode: host
    env_file:
      - ./postgres/vars.env
    volumes:
      - ./postgres/config.sql:/docker-entrypoint-initdb.d/config.sql
      - ./postgres/table.sql:/docker-entrypoint-initdb.d/table.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  # app instancia 01
  app01:
    container_name: app01
    build: 
      context: ./
      dockerfile: app/Dockerfile.app
    hostname: app01
    network_mode: host  
    env_file:
      - ./postgres/vars.env
    environment:
      APP_PORT: 8080 
    ports:
      - 8080:8080 
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  # app instancia 02
  app02:
    container_name: app02
    build: 
      context: ./
      dockerfile: app/Dockerfile.app
    hostname: app02
    network_mode: host  
    env_file:
      - ./postgres/vars.env
    environment:
      APP_PORT: 8081
    ports:
      - 8081:8081
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

