version: '3.8'
services:
  # banco de dados
  postgres:
    container_name: postgres
    image: docker.io/postgres
    hostname: postgres
    network_mode: host
    env_file:
      - ./postgres/vars.env
    volumes:
      - ./postgres/config.sql:/docker-entrypoint-initdb.d/config.sql
      - ./postgres/table.sql:/docker-entrypoint-initdb.d/table.sql
    deploy:
      resources:
        limits:
          #cpus: '0.5'
          memory: '1.0GB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
