FROM docker.io/postgres:15.4

COPY postgres/config.sql /docker-entrypoint-initdb.d/config.sql
COPY postgres/table.sql /docker-entrypoint-initdb.d/table.sql
RUN chown -R postgres.postgres /docker-entrypoint-initdb.d/

