CREATE TABLE IF NOT EXISTS pessoas (
    id VARCHAR(36) CONSTRAINT APELIDO_PK PRIMARY KEY,
    apelido VARCHAR(32) NOT NULL UNIQUE,
    nome VARCHAR(128) NOT NULL,
    nascimento CHAR(10) NOT NULL,
    stack VARCHAR(2048)
);